feat(server): Multiple ContentTypes
Traperto/MagicBytesValidator pull request #66
Opened 2023-09-06 07:04 UTC by maxbreuker

- Support for multiple content types
- Conversion of corresponding positions to string arrays
- Adjusted unit tests

2023-09-06 09:45 UTC, kryptobi requested changes
formatting vs. content changes
What are your current changes?

2023-09-07 07:49 UTC, maxbreuker commented on MagicBytesValidator/Services/Http/FormFileTypeProvider.cs
> +                throw new MimeTypeMismatchException(fileType.MimeTypes.First(), formFile.ContentType);
Use correct content type at exception.

2023-09-07 13:25 UTC, neon-JS approved these changes

2023-09-07 13:46 UTC, kryptobi commented on MagicBytesValidator.Tests/IsValidTests.cs
> +        public async Task Should_validate_2()
.. really?

2023-09-07 13:48 UTC, kryptobi reviewed
check comments

2023-09-07 13:48 UTC, kryptobi commented on MagicBytesValidator.Tests/IsValidTests.cs
> +        public async Task Should_validate_2()
@maxbreuker rename ist.. you are not able to merge the pr before.

2023-09-11 06:53 UTC, kryptobi approved these changes

2023-09-11 10:44 UTC, merged